version: "3"
services:
  s1:
    image: zjoker/bcdns-daemon
    volumes:
      - /var/opt/go/src/BCDns_0.1:/go/src/BCDns_0.1
    networks:
      - test-net
    command: /bin/bash
    tty: true

  s2:
    image: zjoker/bcdns-daemon
    volumes:
      - /var/opt/go/src/BCDns_0.1:/go/src/BCDns_0.1
    networks:
      - test-net
    command: /bin/bash
    tty: true

  s3:
    image: zjoker/bcdns-daemon
    volumes:
      - /var/opt/go/src/BCDns_0.1:/go/src/BCDns_0.1
    networks:
      - test-net
    command: /bin/bash
    tty: true

  s4:
    image: zjoker/bcdns-daemon
    volumes:
      - /var/opt/go/src/BCDns_0.1:/go/src/BCDns_0.1
    networks:
      - test-net
    command: /bin/bash
    tty: true

networks:
  test-net: